//
//  ForgotPasswordBusinessLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 05/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class ForgotPasswordBusinessLogicSpy: ForgotPasswordBusinessLogic {
    var shouldSetupItemsCalled: Bool = false
    
    var shouldUpdateItemCalled: Bool = false
    var shouldValidateItemCalled: Bool = false
    
    var shouldSelectItemCalled: Bool = false
    
    var shouldOpenMailApplicationCalled: Bool = false
    
    func shouldSetupItems() {
        self.shouldSetupItemsCalled = true
    }
    
    func shouldUpdateItem(request: ForgotPasswordModels.UpdateItem.Request) {
        self.shouldUpdateItemCalled = true
    }
    
    func shouldValidateItem(request: ForgotPasswordModels.ValidateItem.Request) {
        self.shouldValidateItemCalled = true
    }
    
    func shouldSelectItem(request: ForgotPasswordModels.ItemSelection.Request) {
        self.shouldSelectItemCalled = true
    }
    
    func shouldOpenMailApplication() {
        self.shouldOpenMailApplicationCalled = true
    }
}
