//
//  PlaceDetailsViewController.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PlaceDetailsViewController: UITableViewController {
    var interactor: PlaceDetailsBusinessLogic?
    var router: (NSObjectProtocol & PlaceDetailsRoutingLogic)?
    
    var place: Place?
    
    // MARK: - Object lifecycle
    
    init(place: Place?) {
        super.init(style: .plain)
        self.setup()
        self.place = place
    }
    
    required init?(coder aDecoder: NSCoder) {
        return nil
    }
    
    // MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = PlaceDetailsInteractor()
        let presenter = PlaceDetailsPresenter()
        let router = PlaceDetailsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.displayer = viewController
        router.viewController = viewController
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setupSubviews()
    }
}
