//
//  MyFavoritePlacesWorker.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 11/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyFavoritePlacesWorkerDelegate: class {
    
}

class MyFavoritePlacesWorker {
    weak var delegate: MyFavoritePlacesWorkerDelegate?
    
    init(delegate: MyFavoritePlacesWorkerDelegate?) {
        self.delegate = delegate
    }
}
