//
//  MainStyle.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainStyle {
    static let shared = MainStyle()
    
    var tabBarViewModel: TabBarViewModel
    var contentViewModel: ContentViewModel
    var tabBarItemViewModel: TabBarItemViewModel
    
    private init() {
        self.tabBarViewModel = TabBarViewModel()
        self.contentViewModel = ContentViewModel()
        self.tabBarItemViewModel = TabBarItemViewModel()
    }
    
    struct TabBarViewModel {
        var isTranslucent: Bool = false
        var barTintColor: UIColor = ApplicationStyle.colors.primaryLight
        var tintColor: UIColor = ApplicationStyle.colors.primary
        var unselectedItemTintColor: UIColor = ApplicationStyle.colors.accent
        var shadowImage: UIImage = UIImage()
    }
    
    struct ContentViewModel {
        var backgroundColor: UIColor = ApplicationStyle.colors.accentAlpha
    }
    
    struct TabBarItemViewModel {
        func selectedTextAttributes() -> [NSAttributedString.Key: Any]? {
            return [
                NSAttributedString.Key.foregroundColor: ApplicationStyle.colors.primary,
                NSAttributedString.Key.font: ApplicationStyle.fonts.regular(size: UIFont.smallSystemFontSize)
            ]
        }
        
        func unselectedTextAttributes() -> [NSAttributedString.Key: Any]? {
            return [
                NSAttributedString.Key.foregroundColor: ApplicationStyle.colors.accent,
                NSAttributedString.Key.font: ApplicationStyle.fonts.regular(size: UIFont.smallSystemFontSize)
            ]
        }
    }
}
