//
//  MainPresenterTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class MainPresenterTests: XCTestCase {
    var sut: MainPresenter!
    var displayerSpy: MainDisplayLogicSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupMainPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupMainPresenter() {
        self.sut = MainPresenter()
        
        self.displayerSpy = MainDisplayLogicSpy()
        self.sut.displayer = self.displayerSpy
    }
    
    // MARK: - Tests
    
    func testPresentSetupScenesShouldAskTheDisplayerToDisplaySetupScenes() {
        self.sut.presentSetupScenes()
        XCTAssertTrue(self.displayerSpy.displaySetupScenesCalled)
    }
    
    func testPresentSelectSceneShouldAskTheDisplayerToDisplaySelectScene() {
        self.sut.presentSelectScene(response: MainModels.SceneSelection.Response(index: 0))
        XCTAssertTrue(self.displayerSpy.displaySelectSceneCalled)
    }
}
