//
//  MyFavoritePlacesWorkerSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 11/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class MyFavoritePlacesWorkerSpy: MyFavoritePlacesWorker {
    var fetchItemsCalled: Bool = false
    var fetchImageCalled: Bool = false
    
    override func fetchItems(userId: String, page: Int, limit: Int) {
        self.fetchItemsCalled = true
    }
    
    override func fetchImage(item: MyFavoritePlacesModels.DisplayedItem) {
        self.fetchImageCalled = true
    }
}
