//
//  FullscreenImageWorkerTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class FullscreenImageWorkerTests: XCTestCase {
    var sut: FullscreenImageWorker!
    var delegateSpy: FullscreenImageWorkerDelegateSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupFullscreenImageWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupFullscreenImageWorker() {
        self.delegateSpy = FullscreenImageWorkerDelegateSpy()
        self.sut = FullscreenImageWorker(delegate: self.delegateSpy)
    }
    
    // MARK: - Tests
    
    func testFetchImage() {
        let taskSpy = ImageTaskSpy()
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(name: "imageName")
        XCTAssertTrue(taskSpy.fetchImageCalled)
    }
    
    func testFetchImageShouldAskTheDelegateToSendImageForSuccessCase() {
        let taskSpy = ImageTaskSpy()
        taskSpy.shouldFailFetchImage = false
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(name: "imageName")
        XCTAssertTrue(self.delegateSpy.successDidFetchImageCalled)
    }
    
    func testFetchImageShouldAskTheDelegateToSendErrorForFailureCase() {
        let taskSpy = ImageTaskSpy()
        taskSpy.shouldFailFetchImage = true
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(name: "imageName")
        XCTAssertTrue(self.delegateSpy.failureDidFetchImageCalled)
    }
}
