//
//  MainRouter.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainRoutingLogic {
    func navigateToOnboarding()
    func dismissViewController()
}

class MainRouter: MainRoutingLogic {
    weak var viewController: MainViewController?
    
    func navigateToOnboarding() {
        let onboardingViewController = OnboardingViewController()
        onboardingViewController.delegate = self.viewController
        let navigationController = UINavigationController(rootViewController: onboardingViewController)
        navigationController.modalPresentationStyle = .fullScreen
        self.viewController?.present(navigationController, animated: true, completion: nil)
    }
    
    func dismissViewController() {
        self.viewController?.dismiss(animated: true, completion: nil)
    }
}
