//
//  MainPresenter.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentSetupScenes()
    func presentSelectScene(response: MainModels.SceneSelection.Response)
    
    func presentNavigateToOnboarding()
    func presentDismissOnboarding()
}

class MainPresenter: MainPresentationLogic {
    weak var displayer: MainDisplayLogic?
    
    func presentSetupScenes() {
        self.displayer?.displaySetupScenes(viewModel: MainModels.ScenesSetup.ViewModel(indices: MainModels.Scenes.allCases.map({ $0.rawValue })))
    }
    
    func presentSelectScene(response: MainModels.SceneSelection.Response) {
        self.displayer?.displaySelectScene(viewModel: MainModels.SceneSelection.ViewModel(index: response.index))
    }
    
    func presentNavigateToOnboarding() {
        self.displayer?.displayNavigateToOnboarding()
    }
    
    func presentDismissOnboarding() {
        self.displayer?.displayDismissOnboarding()
    }
}
