//
//  MainInteractor.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func shouldSelectScene(index: Int) -> Bool
    
    func shouldSetupScenes()
    func shouldSelectInitialScene()
    
    func shouldNavigateToOnboarding(request: MainModels.OnboardingNavigation.Request)
    
    func shouldLoginUser(request: MainModels.UserLogin.Request)
    func shouldLogoutUser()
}

class MainInteractor: MainBusinessLogic, MainWorkerDelegate {
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    
    var user: User?
    var userDefaultsManager: UserDefaultsManager = .shared
    
    init() {
        self.worker = MainWorker(delegate: self)
    }
    
    func shouldSelectScene(index: Int) -> Bool {
        return self.isUserLoggedIn() || index == self.exploreSceneIndex()
    }
    
    func shouldSetupScenes() {
        self.presenter?.presentSetupScenes()
    }
    
    func shouldSelectInitialScene() {
        self.presenter?.presentSelectScene(response: MainModels.SceneSelection.Response(index: self.exploreSceneIndex()))
    }
    
    func shouldNavigateToOnboarding(request: MainModels.OnboardingNavigation.Request) {
        if let index = request.index, index == self.exploreSceneIndex() {
            return
        }
        if !self.isUserLoggedIn() {
            self.presenter?.presentNavigateToOnboarding()
        }
    }
    
    func shouldLoginUser(request: MainModels.UserLogin.Request) {
        self.userDefaultsManager.setUserLoggedIn(value: true)
        self.user = request.user
        
        self.presenter?.presentDismissOnboarding()
    }
    
    func shouldLogoutUser() {
        self.presenter?.presentSelectScene(response: MainModels.SceneSelection.Response(index: self.exploreSceneIndex()))
        
        self.userDefaultsManager.setUserLoggedIn(value: false)
        self.user = nil
    }
}

// MARK: - Auxiliary

extension MainInteractor {
    private func isUserLoggedIn() -> Bool {
        return self.user != nil
    }
    
    private func exploreSceneIndex() -> Int {
        return MainModels.Scenes.explore.rawValue
    }
}
