//
//  MainWorker.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainWorkerDelegate: class {
    
}

class MainWorker {
    weak var delegate: MainWorkerDelegate?
    
    init(delegate: MainWorkerDelegate?) {
        self.delegate = delegate
    }
}
