//
//  SignUpWorkerDelegateSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 06/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class SignUpWorkerDelegateSpy: SignUpWorkerDelegate {
    var successDidSignUpUserCalled: Bool = false
    var failureDidSignUpUserCalled: Bool = false
    
    func successDidSignUpUser(user: User) {
        self.successDidSignUpUserCalled = true
    }
    
    func failureDidSignUpUser(details: SignUpModels.UserDetails, error: OperationError) {
        self.failureDidSignUpUserCalled = true
    }
}
