//
//  SignUpDisplayLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 06/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class SignUpDisplayLogicSpy: SignUpDisplayLogic {
    var displaySetupItemsCalled: Bool = false
    
    var displayUpdateItemCalled: Bool = false
    var displayValidationErrorCalled: Bool = false
    
    var displayUpdateImageItemCalled: Bool = false
    
    var displayActivateTextFieldCalled: Bool = false
    
    var displayEnableItemCalled: Bool = false
    var displayDisableItemCalled: Bool = false
    
    var displayPhotoLibraryAlertCalled: Bool = false
    var displayPhotoLibraryCameraAlertCalled: Bool = false
    var displayPhotoLibraryRemovePhotoAlertCalled: Bool = false
    var displayPhotoLibraryCameraRemovePhotoAlertCalled: Bool = false
    
    var displayCameraAlertCalled: Bool = false
    var displayCameraRemovePhotoAlertCalled: Bool = false
    
    var displayNavigateToPhotoLibraryCalled: Bool = false
    var displayNavigateToCameraCalled: Bool = false
    
    var displayLoadingItemCalled: Bool = false
    var displayNotLoadingItemCalled: Bool = false
    
    var displayEnableUserInteractionCalled: Bool = false
    var displayDisableUserInteractionCalled: Bool = false
    
    var displayUserDetailsCalled: Bool = false
    var displayErrorDetailsCalled: Bool = false
    
    func displaySetupItems(viewModel: SignUpModels.SetupItems.ViewModel) {
        self.displaySetupItemsCalled = true
    }
    
    func displayUpdateItem(viewModel: SignUpModels.UpdateItem.ViewModel) {
        self.displayUpdateItemCalled = true
    }
    
    func displayValidationError(viewModel: SignUpModels.ValidateItem.ViewModel) {
        self.displayValidationErrorCalled = true
    }
    
    func displayUpdateImageItem(viewModel: SignUpModels.UpdateImageItem.ViewModel) {
        self.displayUpdateImageItemCalled = true
    }
    
    func displayActivateTextField(viewModel: SignUpModels.ActivateTextField.ViewModel) {
        self.displayActivateTextFieldCalled = true
    }
    
    func displayEnableItem(viewModel: SignUpModels.EnableItem.ViewModel) {
        self.displayEnableItemCalled = true
    }
    
    func displayDisableItem(viewModel: SignUpModels.EnableItem.ViewModel) {
        self.displayDisableItemCalled = true
    }
    
    func displayPhotoLibraryAlert(viewModel: SignUpModels.PhotoLibraryAlert.ViewModel) {
        self.displayPhotoLibraryAlertCalled = true
    }
    
    func displayPhotoLibraryCameraAlert(viewModel: SignUpModels.PhotoLibraryCameraAlert.ViewModel) {
        self.displayPhotoLibraryCameraAlertCalled = true
    }
    
    func displayPhotoLibraryRemovePhotoAlert(viewModel: SignUpModels.PhotoLibraryRemovePhotoAlert.ViewModel) {
        self.displayPhotoLibraryRemovePhotoAlertCalled = true
    }
    
    func displayPhotoLibraryCameraRemovePhotoAlert(viewModel: SignUpModels.PhotoLibraryCameraRemovePhotoAlert.ViewModel) {
        self.displayPhotoLibraryCameraRemovePhotoAlertCalled = true
    }
    
    func displayCameraAlert(viewModel: SignUpModels.CameraAlert.ViewModel) {
        self.displayCameraAlertCalled = true
    }
    
    func displayCameraRemovePhotoAlert(viewModel: SignUpModels.CameraRemovePhotoAlert.ViewModel) {
        self.displayCameraRemovePhotoAlertCalled = true
    }
    
    func displayNavigateToPhotoLibrary(viewModel: SignUpModels.SourceView.ViewModel) {
        self.displayNavigateToPhotoLibraryCalled = true
    }
    
    func displayNavigateToCamera(viewModel: SignUpModels.SourceView.ViewModel) {
        self.displayNavigateToCameraCalled = true
    }
    
    func displayLoadingItem(viewModel: SignUpModels.LoadingItem.ViewModel) {
        self.displayLoadingItemCalled = true
    }
    
    func displayNotLoadingItem(viewModel: SignUpModels.LoadingItem.ViewModel) {
        self.displayNotLoadingItemCalled = true
    }
    
    func displayEnableUserInteraction() {
        self.displayEnableUserInteractionCalled = true
    }
    
    func displayDisableUserInteraction() {
        self.displayDisableUserInteractionCalled = true
    }
    
    func displayUserDetails(viewModel: SignUpModels.SignUpUser.ViewModel) {
        self.displayUserDetailsCalled = true
    }
    
    func displayErrorDetails(viewModel: SignUpModels.SignUpError.ViewModel) {
        self.displayErrorDetailsCalled = true
    }
}
