//
//  SignUpBusinessLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 06/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class SignUpBusinessLogicSpy: SignUpBusinessLogic {
    var shouldSetupItemsCalled: Bool = false
    
    var shouldUpdateItemCalled: Bool = false
    var shouldValidateItemCalled: Bool = false
    var shouldSelectItemCalled: Bool = false
    
    var shouldUpdateImageItemCalled: Bool = false
    
    var shouldActivateTextFieldCalled: Bool = false
    
    var shouldNavigateToPhotoLibraryCalled: Bool = false
    var shouldNavigateToCameraCalled: Bool = false
    
    func shouldSetupItems() {
        self.shouldSetupItemsCalled = true
    }
    
    func shouldUpdateItem(request: SignUpModels.UpdateItem.Request) {
        self.shouldUpdateItemCalled = true
    }
    
    func shouldValidateItem(request: SignUpModels.ValidateItem.Request) {
        self.shouldValidateItemCalled = true
    }
    
    func shouldSelectItem(request: SignUpModels.ItemSelection.Request) {
        self.shouldSelectItemCalled = true
    }
    
    func shouldUpdateImageItem(request: SignUpModels.UpdateImageItem.Request) {
        self.shouldUpdateImageItemCalled = true
    }
    
    func shouldActivateTextField(request: SignUpModels.ActivateTextField.Request) {
        self.shouldActivateTextFieldCalled = true
    }
    
    func shouldNavigateToPhotoLibrary(request: SignUpModels.SourceView.Request) {
        self.shouldNavigateToPhotoLibraryCalled = true
    }
    
    func shouldNavigateToCamera(request: SignUpModels.SourceView.Request) {
        self.shouldNavigateToCameraCalled = true
    }
}
