//
//  PlaceDetailsLocalization.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PlaceDetailsLocalization {
    static let shared = PlaceDetailsLocalization()
    
    private init() {
        
    }
    
    struct LocalizedKey {
        static let
        errorStateText = "PlaceDetails.scene.error.state.text",
        errorAlertMessage = "PlaceDetails.scene.error.alert.message",
        errorAlertCancelTitle = "PlaceDetails.scene.error.alert.cancel.title",
        
        commentCount = "PlaceDetails.scene.comment.count"
    }
    
    let errorStateText = LocalizedKey.errorStateText.localized()
    let errorAlertMessage = LocalizedKey.errorAlertMessage.localized()
    let errorAlertCancelTitle = LocalizedKey.errorAlertCancelTitle.localized()
    
    func commentCount(_ count: Int) -> String {
        return String.localizedStringWithFormat(LocalizedKey.commentCount.localized(), count)
    }
}
