//
//  LoginPresentationLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class LoginPresentationLogicSpy: LoginPresentationLogic {
    var presentSetupItemsCalled: Bool = false
    
    var presentUpdateItemCalled: Bool = false
    
    var presentValidationErrorCalled: Bool = false
    
    var presentActivateTextFieldCalled: Bool = false
    
    var presentEnableItemCalled: Bool = false
    var presentDisableItemCalled: Bool = false
    
    var presentLoadingItemCalled: Bool = false
    var presentNotLoadingItemCalled: Bool = false
    
    var presentEnableUserInteractionCalled: Bool = false
    var presentDisableUserInteractionCalled: Bool = false
    
    var presentNavigateToForgotPasswordCalled: Bool = false
    
    var presentErrorAlertCalled: Bool = false
    
    var presentUserDetailsCalled: Bool = false
    
    func presentSetupItems() {
        self.presentSetupItemsCalled = true
    }
    
    func presentUpdateItem(response: LoginModels.UpdateItem.Response) {
        self.presentUpdateItemCalled = true
    }
    
    func presentValidationError(response: LoginModels.ValidateItem.Response) {
        self.presentValidationErrorCalled = true
    }
    
    func presentActivateTextField(response: LoginModels.ActivateTextField.Response) {
        self.presentActivateTextFieldCalled = true
    }
    
    func presentEnableItem(response: LoginModels.EnableItem.Response) {
        self.presentEnableItemCalled = true
    }
    
    func presentDisableItem(response: LoginModels.EnableItem.Response) {
        self.presentDisableItemCalled = true
    }
    
    func presentLoadingItem(response: LoginModels.LoadingItem.Response) {
        self.presentLoadingItemCalled = true
    }
    
    func presentNotLoadingItem(response: LoginModels.LoadingItem.Response) {
        self.presentNotLoadingItemCalled = true
    }
    
    func presentEnableUserInteraction() {
        self.presentEnableUserInteractionCalled = true
    }
    
    func presentDisableUserInteraction() {
        self.presentDisableUserInteractionCalled = true
    }
    
    func presentNavigateToForgotPassword() {
        self.presentNavigateToForgotPasswordCalled = true
    }
    
    func presentErrorAlert(response: LoginModels.LoginError.Response) {
        self.presentErrorAlertCalled = true
    }
    
    func presentUserDetails(response: LoginModels.UserDetails.Response) {
        self.presentUserDetailsCalled = true
    }
}
