//
//  LoginWorkerDelegateSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class LoginWorkerDelegateSpy: LoginWorkerDelegate {
    var successDidLoginUserCalled: Bool = false
    var failureDidLoginUserCalled: Bool = false
    
    func successDidLoginUser(user: User) {
        self.successDidLoginUserCalled = true
    }
    
    func failureDidLoginUser(details: LoginModels.LoginDetails, error: OperationError) {
        self.failureDidLoginUserCalled = true
    }
}
