//
//  PlaceCommentsRouterTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class PlaceCommentsRouterTests: XCTestCase {
    var sut: PlaceCommentsRouter!
    var viewController: PlaceCommentsViewController!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupPlaceCommentsRouter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupPlaceCommentsRouter() {
        self.sut = PlaceCommentsRouter()
        
        self.viewController = PlaceCommentsViewController(placeId: "placeId")
        self.sut.viewController = self.viewController
    }
    
    // MARK: - Tests
    
    
}
