//
//  PlaceCommentsInteractorTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class PlaceCommentsInteractorTests: XCTestCase {
    var sut: PlaceCommentsInteractor!
    var presenterSpy: PlaceCommentsPresentationLogicSpy!
    var workerSpy: PlaceCommentsWorkerSpy!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        self.setupPlaceCommentsInteractor()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupPlaceCommentsInteractor() {
        self.sut = PlaceCommentsInteractor()
        
        self.presenterSpy = PlaceCommentsPresentationLogicSpy()
        self.sut.presenter = self.presenterSpy
        
        self.workerSpy = PlaceCommentsWorkerSpy(delegate: self.sut)
        self.sut.worker = self.workerSpy
    }
    
    // MARK: - Tests
  
    
}
