//
//  ExploreBusinessLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class ExploreBusinessLogicSpy: ExploreBusinessLogic {
    var shouldFetchItemsCalled: Bool = false
    var shouldFetchImageCalled: Bool = false
    
    var shouldBeginSearchStateCalled: Bool = false
    var shouldEndSearchStateCalled: Bool = false
    var shouldSearchItemsCalled: Bool = false
    
    var shouldNavigateToPlaceDetailsCalled: Bool = false
    
    func shouldFetchItems() {
        self.shouldFetchItemsCalled = true
    }
    
    func shouldFetchImage(request: ExploreModels.ImageFetching.Request) {
        self.shouldFetchImageCalled = true
    }
    
    func shouldBeginSearchState() {
        self.shouldBeginSearchStateCalled = true
    }
    
    func shouldEndSearchState() {
        self.shouldEndSearchStateCalled = true
    }
    
    func shouldSearchItems(request: ExploreModels.ItemsSearching.Request) {
        self.shouldSearchItemsCalled = true
    }
    
    func shouldNavigateToPlaceDetails(request: ExploreModels.ItemNavigation.Request) {
        self.shouldNavigateToPlaceDetailsCalled = true
    }
}
