//
//  FullscreenImageDisplayLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class FullscreenImageDisplayLogicSpy: FullscreenImageDisplayLogic {
    var displayWillFetchImageCalled: Bool = false
    var displayDidFetchImageCalled: Bool = false
    var displayImageCalled: Bool = false
    
    func displayWillFetchImage() {
        self.displayWillFetchImageCalled = true
    }
    
    func displayDidFetchImage() {
        self.displayDidFetchImageCalled = true
    }
    
    func displayImage(viewModel: FullscreenImageModels.ImagePresentation.ViewModel) {
        self.displayImageCalled = true
    }
}
