//
//  MyProfileWorker.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyProfileWorkerDelegate: class {
    func successDidFetchUser(user: User)
    func failureDidFetchUser(error: OperationError)
    
    func successDidFetchImage(model: MyProfileModels.UserModel, image: UIImage?)
    func failureDidFetchImage(model: MyProfileModels.UserModel, error: OperationError)
    
    func successDidLogoutUser(userId: String?)
    func failureDidLogoutUser(error: OperationError)
}

class MyProfileWorker {
    weak var delegate: MyProfileWorkerDelegate?
    
    var usersTask: UsersTaskProtocol = TaskConfigurator.shared.usersTask()
    var imageTask: ImageTaskProtocol = TaskConfigurator.shared.imageTask()
    var authenticationTask: AuthenticationTaskProtocol = TaskConfigurator.shared.authenticationTask()
    
    init(delegate: MyProfileWorkerDelegate?) {
        self.delegate = delegate
    }
    
    func fetchUser(userId: String?) {
        self.usersTask.fetchUser(model: UsersTaskModels.FetchUser.Request(userId: userId)) { result in
            switch result {
                case .success(let response): self.delegate?.successDidFetchUser(user: response.user); break
                case .failure(let error): self.delegate?.failureDidFetchUser(error: error); break
            }
        }
    }
    
    func fetchImage(model: MyProfileModels.UserModel) {
        self.imageTask.fetchImage(model: ImageTaskModels.Fetch.Request(imageName: model.imageName)) { result in
            switch result {
                case .success(let response): self.delegate?.successDidFetchImage(model: model, image: response.image); break
                case .failure(let error): self.delegate?.failureDidFetchImage(model: model, error: error); break
            }
        }
    }
    
    func logoutUser(userId: String?) {
        self.authenticationTask.logoutUser(model: AuthenticationTaskModels.LogoutUser.Request(userId: userId)) { result in
            switch result {
                case .success(let response): self.delegate?.successDidLogoutUser(userId: response.userId); break
                case .failure(let error): self.delegate?.failureDidLogoutUser(error: error); break
            }
        }
    }
}
