//
//  MyProfileInteractor.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyProfileBusinessLogic {
    
}

class MyProfileInteractor: MyProfileBusinessLogic {
    var presenter: MyProfilePresentationLogic?
    var worker: MyProfileWorker?
    
    init() {
        self.worker = MyProfileWorker(delegate: self)
    }
    
    func successDidFetchUser(user: User) {
        
    }
    
    func failureDidFetchUser(error: OperationError) {
        
    }
}

extension MyProfileInteractor: MyProfileWorkerDelegate {
    func successDidFetchImage(model: MyProfileModels.UserModel, image: UIImage?) {
        
    }
    
    func failureDidFetchImage(model: MyProfileModels.UserModel, error: OperationError) {
        
    }
}
