//
//  FullscreenImagePresenter.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullscreenImagePresentationLogic {
    func presentWillFetchImage()
    func presentDidFetchImage()
    func presentImage(response: FullscreenImageModels.ImagePresentation.Response)
    func presentPlaceholderImage()
}

class FullscreenImagePresenter: FullscreenImagePresentationLogic {
    weak var displayer: FullscreenImageDisplayLogic?
    
    func presentWillFetchImage() {
        self.displayer?.displayWillFetchImage()
    }
    
    func presentDidFetchImage() {
        self.displayer?.displayDidFetchImage()
    }
    
    func presentImage(response: FullscreenImageModels.ImagePresentation.Response) {
        self.displayer?.displayImage(viewModel: FullscreenImageModels.ImagePresentation.ViewModel(image: response.image, contentMode: .scaleAspectFit))
    }
    
    func presentPlaceholderImage() {
        let image = FullscreenImageStyle.shared.loadingImageViewModel.placeholderImage
        self.displayer?.displayImage(viewModel: FullscreenImageModels.ImagePresentation.ViewModel(image: image, contentMode: .center))
    }
}
