//
//  FullscreenImageModels.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FullscreenImageModels {
    struct ImageSetup {
        struct Request {
            let name: String?
        }
    }
    
    struct ImagePresentation {
        struct Response {
            let image: UIImage?
        }
        
        struct ViewModel {
            let image: UIImage?
            let contentMode: UIView.ContentMode
        }
    }
}
