//
//  MyProfileBusinessLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class MyProfileBusinessLogicSpy: MyProfileBusinessLogic {
    var shouldFetchUserCalled: Bool = false
    var shouldFetchImageCalled: Bool = false
    var shouldSelectItemCalled: Bool = false
    
    func shouldFetchUser() {
        self.shouldFetchUserCalled = true
    }
    
    func shouldFetchImage(request: MyProfileModels.ImageFetching.Request) {
        self.shouldFetchImageCalled = true
    }
    
    func shouldSelectItem(request: MyProfileModels.ItemSelection.Request) {
        self.shouldSelectItemCalled = true
    }
}
