//
//  MyProfileWorkerDelegateSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import UIKit

class MyProfileWorkerDelegateSpy: MyProfileWorkerDelegate {
    var successDidFetchUserCalled: Bool = false
    var failureDidFetchUserCalled: Bool = false
    
    var successDidFetchImageCalled: Bool = false
    var failureDidFetchImageCalled: Bool = false
    
    var successDidLogoutUserCalled: Bool = false
    var failureDidLogoutUserCalled: Bool = false
    
    func successDidFetchUser(user: User) {
        self.successDidFetchUserCalled = true
    }
    
    func failureDidFetchUser(error: OperationError) {
        self.failureDidFetchUserCalled = true
    }
    
    func successDidFetchImage(model: MyProfileModels.UserModel, image: UIImage?) {
        self.successDidFetchImageCalled = true
    }
    
    func failureDidFetchImage(model: MyProfileModels.UserModel, error: OperationError) {
        self.failureDidFetchImageCalled = true
    }
    
    func successDidLogoutUser(userId: String?) {
        self.successDidLogoutUserCalled = true
    }
    
    func failureDidLogoutUser(error: OperationError) {
        self.failureDidLogoutUserCalled = true
    }
}
