//
//  MyProfileWorkerDelegateSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import UIKit

class MyProfileWorkerDelegateSpy: MyProfileWorkerDelegate {
    var successDidFetchImageCalled: Bool = false
    var failureDidFetchImageCalled: Bool = false
    
    func successDidFetchImage(model: MyProfileModels.UserModel, image: UIImage?) {
        self.successDidFetchImageCalled = true
    }
    
    func failureDidFetchImage(model: MyProfileModels.UserModel, error: OperationError) {
        self.failureDidFetchImageCalled = true
    }
}
