//
//  MyProfileRoutingLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import UIKit

class MyProfileRoutingLogicSpy: MyProfileRoutingLogic {
    var navigateToEmailCalled: Bool = false
    var navigateToAlertCalled: Bool = false
    var navigateToFullscreenImageCalled: Bool = false
    
    func navigateToEmail(recipient: String, subject: String) {
        self.navigateToEmailCalled = true
    }
    
    func navigateToAlert(title: String?, message: String?, actions: [UIAlertAction]) {
        self.navigateToAlertCalled = true
    }
    
    func navigateToFullscreenImage(imageName: String?) {
        self.navigateToFullscreenImageCalled = true
    }
}
