//
//  MyProfileLocalization.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MyProfileLocalization {
    static let shared = MyProfileLocalization()
    
    private init() {
        
    }
    
    struct LocalizedKey {
        static let
        title = "MyProfile.scene.title",
        logoutTitle = "MyProfile.scene.logout.title",
        reportIssueTitle = "MyProfile.scene.report.issue.title",
        versionTitle = "MyProfile.scene.version.title",
        reportIssueEmailSubject = "MyProfile.scene.report.issue.email.subject"
    }
    
    let title = LocalizedKey.title.localized()
    let logoutTitle = LocalizedKey.logoutTitle.localized()
    let reportIssueTitle = LocalizedKey.reportIssueTitle.localized()
    
    func reportIssueEmailSubject(applicationName: String, applicationVersion: String) -> String {
        return String(format: LocalizedKey.reportIssueEmailSubject.localized(), applicationName, applicationVersion)
    }
    
    func versionTitle(version: String) -> String {
        return String(format: LocalizedKey.versionTitle.localized(), version)
    }
}
