//
//  OnboardingStyle.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OnboardingStyle {
    static let shared = OnboardingStyle()
    
    var contentViewModel: ContentViewModel
    var dismissButtonModel: DismissButtonModel
    var logoImageViewModel: LogoImageViewModel
    var loginButtonModel: LoginButtonModel
    var signUpButtonModel: SignUpButtonModel
    
    private init() {
        self.contentViewModel = ContentViewModel()
        self.dismissButtonModel = DismissButtonModel()
        self.logoImageViewModel = LogoImageViewModel()
        self.loginButtonModel = LoginButtonModel()
        self.signUpButtonModel = SignUpButtonModel()
    }
    
    struct ContentViewModel {
        var backgroundColor = ApplicationStyle.colors.primaryLight
    }
    
    struct DismissButtonModel {
        var image: UIImage = ApplicationStyle.images.closeIcon
        var tintColor: UIColor = ApplicationStyle.colors.primary
    }
    
    struct LogoImageViewModel {
        var image = ApplicationStyle.images.logoIcon.withRenderingMode(.alwaysTemplate)
        var tintColor = ApplicationStyle.colors.primary
        var size: CGFloat = 150
    }
    
    struct LoginButtonModel {
        func titleAttributes() -> [NSAttributedString.Key: Any] {
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.alignment = .center
            return [
                NSAttributedString.Key.foregroundColor: ApplicationStyle.colors.primaryLight,
                NSAttributedString.Key.font: ApplicationStyle.fonts.preferredFont(style: .callout),
                NSAttributedString.Key.paragraphStyle: paragraphStyle
            ]
        }
        
        var backgroundColor = ApplicationStyle.colors.primary
        var borderWidth: CGFloat = 1 / UIScreen.main.scale
        var borderColor = ApplicationStyle.colors.primaryLight.cgColor
        var cornerRadius: CGFloat = 5
        var contentEdgeInsets = UIEdgeInsets(top: 15, left: 15, bottom: 15, right: 15)
    }
    
    struct SignUpButtonModel {
        func titleAttributes() -> [NSAttributedString.Key: Any] {
            let paragraphStyle = NSMutableParagraphStyle()
            paragraphStyle.alignment = .center
            return [
                NSAttributedString.Key.foregroundColor: ApplicationStyle.colors.primaryLight,
                NSAttributedString.Key.font: ApplicationStyle.fonts.preferredFont(style: .callout),
                NSAttributedString.Key.paragraphStyle: paragraphStyle
            ]
        }
        
        var backgroundColor = ApplicationStyle.colors.primary
        var borderWidth: CGFloat = 1 / UIScreen.main.scale
        var borderColor = ApplicationStyle.colors.primaryLight.cgColor
        var cornerRadius: CGFloat = 5
        var contentEdgeInsets = UIEdgeInsets(top: 15, left: 15, bottom: 15, right: 15)
    }
}
