//
//  ForgotPasswordLocalization.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 05/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ForgotPasswordLocalization {
    static let shared = ForgotPasswordLocalization()
    
    private init() {
        
    }
    
    struct LocalizedKey {
        static let
        forgotPasswordTitle = "ForgotPassword.scene.title",
        emailTitle = "ForgotPassword.scene.email.title",
        sendResetLinkButtonTitle = "ForgotPassword.scene.send.reset.link.button.title",
        emailErrorText = "ForgotPassword.scene.email.error.text",
        confirmationMessage = "ForgotPassword.scene.confirmation.message",
        errorMessage = "ForgotPassword.scene.generic.error.message",
        goToMailTitle = "ForgotPassword.scene.go.to.mail.title",
        okTitle = "ForgotPassword.scene.ok.title"
    }
    
    let forgotPasswordTitle = LocalizedKey.forgotPasswordTitle.localized()
    let emailTitle = LocalizedKey.emailTitle.localized()
    let sendResetLinkButtonTitle = LocalizedKey.sendResetLinkButtonTitle.localized()
    let emailErrorText = LocalizedKey.emailErrorText.localized()
    let errorMessage = LocalizedKey.errorMessage.localized()
    let goToMailTitle = LocalizedKey.goToMailTitle.localized()
    let okTitle = LocalizedKey.okTitle.localized()
    
    func confirmationMessage(email: String) -> String {
        return String.localizedStringWithFormat(LocalizedKey.confirmationMessage.localized(), email)
    }
}
