//
//  OnboardingWorker.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnboardingWorkerDelegate: class {
    
}

class OnboardingWorker {
    weak var delegate: OnboardingWorkerDelegate?
    
    init(delegate: OnboardingWorkerDelegate?) {
        self.delegate = delegate
    }
}
