//
//  ForgotPasswordRouter.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 05/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordRoutingLogic {
    func popViewController()
    func navigateToAlert(title: String?, message: String?, actions: [UIAlertAction])
    func navigateToApplication(url: URL)
}

class ForgotPasswordRouter: ForgotPasswordRoutingLogic {
    weak var viewController: ForgotPasswordViewController?
    
    var urlOpener: URLOpenable = UIApplication.shared
    
    func popViewController() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
    func navigateToAlert(title: String?, message: String?, actions: [UIAlertAction]) {
        let alertController = UIAlertController(title: title, message: message, preferredStyle: UIAlertController.Style.alert)
        actions.forEach({ alertController.addAction($0) })
        self.viewController?.present(alertController, animated: true, completion: nil)
    }
    
    func navigateToApplication(url: URL) {
        self.urlOpener.open(url, options: [:], completionHandler: nil)
    }
}
