//
//  PlaceDetailsRoutingLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import UIKit

class PlaceDetailsRoutingLogicSpy: PlaceDetailsRoutingLogic {
    var navigateToAlertCalled: Bool = false
    var navigateToFullscreenImageCalled: Bool = false
        
    func navigateToAlert(title: String?, message: String?, actions: [UIAlertAction]) {
        self.navigateToAlertCalled = true
    }
    
    func navigateToFullscreenImage(imageName: String?) {
        self.navigateToFullscreenImageCalled = true
    }
}
