//
//  PlaceDetailsWorkerDelegateSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import UIKit

class PlaceDetailsWorkerDelegateSpy: PlaceDetailsWorkerDelegate {
    var successDidFetchImageCalled: Bool = false
    var failureDidFetchPlaceCalled: Bool = false
    
    var successDidFetchPlaceCalled: Bool = false
    var failureDidFetchImageCalled: Bool = false
    
    func successDidFetchImage(model: PlaceDetailsModels.PhotoModel, image: UIImage?) {
        self.successDidFetchImageCalled = true
    }
    
    func failureDidFetchPlace(error: OperationError) {
        self.failureDidFetchPlaceCalled = true
    }
    
    func successDidFetchPlace(place: Place) {
        self.successDidFetchPlaceCalled = true
    }
    
    func failureDidFetchImage(model: PlaceDetailsModels.PhotoModel, error: OperationError) {
        self.failureDidFetchImageCalled = true
    }
}
