//
//  PlaceDetailsDisplayLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class PlaceDetailsDisplayLogicSpy: PlaceDetailsDisplayLogic {
    var displayWillFetchPlaceCalled: Bool = false
    var displayDidFetchPlaceCalled: Bool = false
    
    var displayPlaceCalled: Bool = false
    var displayPlaceViewModel: PlaceDetailsModels.PlacePresentation.ViewModel!
    var displayResetPlaceCalled: Bool = false
    
    var displayWillFetchImageCalled: Bool = false
    var displayDidFetchImageCalled: Bool = false
    var displayImageCalled: Bool = false
    
    var displayErrorStateCalled: Bool = false
    var displayRemoveErrorStateCalled: Bool = false
    
    var displayErrorAlertCalled: Bool = false
    
    var displayNavigateToFullscreenImageCalled: Bool = false
    
    var displayPlaceTitleCalled: Bool = false
    var displaySharePlaceCalled: Bool = false
    
    func displayWillFetchPlace() {
        self.displayWillFetchPlaceCalled = true
    }
    
    func displayDidFetchPlace() {
        self.displayDidFetchPlaceCalled = true
    }
    
    func displayPlace(viewModel: PlaceDetailsModels.PlacePresentation.ViewModel) {
        self.displayPlaceCalled = true
        self.displayPlaceViewModel = viewModel
    }
    
    func displayResetPlace() {
        self.displayResetPlaceCalled = true
    }
    
    func displayWillFetchImage(viewModel: PlaceDetailsModels.ImageFetching.ViewModel) {
        self.displayWillFetchImageCalled = true
    }
    
    func displayDidFetchImage(viewModel: PlaceDetailsModels.ImageFetching.ViewModel) {
        self.displayDidFetchImageCalled = true
    }
    
    func displayImage(viewModel: PlaceDetailsModels.ImagePresentation.ViewModel) {
        self.displayImageCalled = true
    }
    
    func displayErrorState(viewModel: PlaceDetailsModels.ErrorStatePresentation.ViewModel) {
        self.displayErrorStateCalled = true
    }
    
    func displayRemoveErrorState() {
        self.displayRemoveErrorStateCalled = true
    }
    
    func displayErrorAlert(viewModel: PlaceDetailsModels.ErrorAlertPresentation.ViewModel) {
        self.displayErrorAlertCalled = true
    }
    
    func displayNavigateToFullscreenImage(viewModel: PlaceDetailsModels.FullscreenImageNavigation.ViewModel) {
        self.displayNavigateToFullscreenImageCalled = true
    }
    
    func displayPlaceTitle(viewModel: PlaceDetailsModels.TitlePresentation.ViewModel) {
        self.displayPlaceTitleCalled = true
    }
    
    func displaySharePlace(viewModel: PlaceDetailsModels.PlaceSharing.ViewModel) {
        self.displaySharePlaceCalled = true
    }
}
