//
//  LoginViewController+Subviews.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 04/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

extension LoginViewController {
    func setupSubviews() {
        self.setupNavigationBar()
        self.setupNavigationItem()
        self.setupContentView()
        self.setupTableView()
    }
    
    func showNavigationBar() {
        self.navigationController?.setNavigationBarHidden(false, animated: false)
    }
    
    private func setupNavigationBar() {
        self.navigationController?.navigationBar.isTranslucent = LoginStyle.shared.navigationBarModel.isTranslucent
        self.navigationController?.navigationBar.tintColor = LoginStyle.shared.navigationBarModel.tintColor
        self.navigationController?.navigationBar.barTintColor = LoginStyle.shared.navigationBarModel.barTintColor
        self.navigationController?.navigationBar.titleTextAttributes = LoginStyle.shared.navigationBarModel.titleAttributes()
    }
    
    private func setupNavigationItem() {
        self.navigationItem.title = LoginLocalization.shared.loginTitle
    }
    
    private func setupContentView() {
        self.view.backgroundColor = LoginStyle.shared.contentViewModel.backgroundColor
    }
        
    private func setupTableView() {
        self.tableView?.separatorStyle = .none
        self.tableView?.register(LoginTextFieldCell.self, forCellReuseIdentifier: LoginTextFieldCell.defaultReuseIdentifier)
        self.tableView?.register(LoginButtonCell.self, forCellReuseIdentifier: LoginButtonCell.defaultReuseIdentifier)
        self.tableView?.register(LoginForgotPasswordButtonCell.self, forCellReuseIdentifier: LoginForgotPasswordButtonCell.defaultReuseIdentifier)
    }
}
