//
//  SignUpRouterTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 06/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class SignUpRouterTests: XCTestCase {
    var sut: SignUpRouter!
    var viewControllerSpy: SignUpViewControllerSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupSignUpRouter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupSignUpRouter() {
        self.sut = SignUpRouter()
        
        self.viewControllerSpy = SignUpViewControllerSpy()
        self.sut.viewController = self.viewControllerSpy
    }
    
    // MARK: - Tests
    
    func testPopViewController() {
        let navigationControllerSpy = UINavigationControllerSpy(rootViewController: self.sut.viewController!)
        self.sut.popViewController()
        XCTAssertTrue(navigationControllerSpy.popViewControllerCalled)
    }
    
    func testDismissViewController() {
        self.sut.dismissViewController()
        XCTAssertTrue(self.viewControllerSpy.dismissCalled)
    }
    
    func testNavigateToAlert() {
        self.sut.navigateToAlert(title: "title", message: "message", actions: [])
        XCTAssertTrue(self.viewControllerSpy.presentCalled)
    }
    
    func testNavigateToActionSheet() {
        self.sut.navigateToActionSheet(actions: [], sourceView: UIView())
        XCTAssertTrue(self.viewControllerSpy.presentCalled)
    }
    
    func testNavigateToPhotoLibrary() {
        self.sut.navigateToPhotoLibrary(sourceView: UIView())
        XCTAssertTrue(self.viewControllerSpy.presentCalled)
    }
    
    func testNavigateToCamera() {
        self.sut.navigateToCamera(sourceView: UIView())
        XCTAssertTrue(self.viewControllerSpy.presentCalled)
    }
}
