//
//  ExploreLocalization.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ExploreLocalization {
    static let shared = ExploreLocalization()
    
    private init() {
        
    }
    
    struct LocalizedKey {
        static let
        title = "Explore.scene.title",
        emptyStateText = "Explore.scene.empty.state.text",
        noMorePlacesText = "Explore.scene.no.more.places.text",
        errorStateText = "Explore.scene.error.state.text"
    }
    
    let title = LocalizedKey.title.localized()
    let emptyStateText = LocalizedKey.emptyStateText.localized()
    let noMorePlacesText = LocalizedKey.noMorePlacesText.localized()
    let errorStateText = LocalizedKey.errorStateText.localized()
}
