//
//  MainBusinessLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class MainBusinessLogicSpy: MainBusinessLogic {
    var shouldSetupScenesCalled: Bool = false
    var shouldSelectInitialSceneCalled: Bool = false
    
    func shouldSetupScenes() {
        self.shouldSetupScenesCalled = true
    }
    
    func shouldSelectInitialScene() {
        self.shouldSelectInitialSceneCalled = true
    }
}
