//
//  MainPresentationLogicSpy.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling

class MainPresentationLogicSpy: MainPresentationLogic {
    var presentSetupScenesCalled: Bool = false
    var presentSelectSceneCalled: Bool = false
    
    var presentNavigateToOnboardingCalled: Bool = false
    var presentDismissOnboardingCalled: Bool = false
    
    var presentLoginUserCalled: Bool = false
    var presentLogoutUserCalled: Bool = false
    
    func presentSetupScenes() {
        self.presentSetupScenesCalled = true
    }
    
    func presentSelectScene(response: MainModels.SceneSelection.Response) {
        self.presentSelectSceneCalled = true
    }
    
    func presentNavigateToOnboarding() {
        self.presentNavigateToOnboardingCalled = true
    }
    
    func presentDismissOnboarding() {
        self.presentDismissOnboardingCalled = true
    }
    
    func presentLoginUser(response: MainModels.UserLogin.Response) {
        self.presentLoginUserCalled = true
    }
    
    func presentLogoutUser() {
        self.presentLogoutUserCalled = true
    }
}
