//
//  ExploreRouter.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExploreRoutingLogic {
    func navigateToPlaceDetails(place: Place)
}

class ExploreRouter: ExploreRoutingLogic {
    weak var viewController: ExploreViewController?
    
    func navigateToPlaceDetails(place: Place) {
        // TODO: - Replace with place details view controller!
        let placeDetailsViewController = UIViewController()
        placeDetailsViewController.hidesBottomBarWhenPushed = true
        self.viewController?.navigationController?.pushViewController(placeDetailsViewController, animated: true)
    }
}
