//
//  ExploreInteractor.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExploreBusinessLogic {
    func shouldFetchItems()
}

class ExploreInteractor: ExploreBusinessLogic {
    var presenter: ExplorePresentationLogic?
    var worker: ExploreWorker?
    
    var paginationModel: ExploreModels.PaginationModel
    
    init() {
        self.paginationModel = ExploreModels.PaginationModel()
        self.worker = ExploreWorker(delegate: self)
    }
    
    func shouldFetchItems() {
        if !self.paginationModel.isFetchingItems && !self.paginationModel.noMoreItems {
            self.paginationModel.isFetchingItems = true
            self.presenter?.presentWillFetchItems()
            self.worker?.fetchItems(page: self.paginationModel.currentPage, limit: self.paginationModel.limit)
        }
    }
}

extension ExploreInteractor: ExploreWorkerDelegate {
    func successDidFetchItems(items: [Place]) {
        self.paginationModel.items.append(contentsOf: items)
        self.paginationModel.currentPage += 1
        self.paginationModel.isFetchingItems = false
        self.paginationModel.hasError = false
        self.presenter?.presentDidFetchItems()
        self.presenter?.presentRemoveErrorState()
        self.presenter?.presentItems(response: ExploreModels.ItemsPresentation.Response(items: items))
        self.shouldVerifyNoMorePlaces(count: items.count)
        self.shouldVerifyEmptyState(count: items.count)
    }
    
    func failureDidFetchItems(error: OperationError) {
        self.paginationModel.isFetchingItems = false
        self.paginationModel.hasError = true
        self.presenter?.presentDidFetchItems()
        self.presenter?.presentErrorState()
    }
}

extension ExploreInteractor {
    private func shouldVerifyNoMorePlaces(count: Int) {
        if count < self.paginationModel.limit {
            self.paginationModel.noMoreItems = true
            self.presenter?.presentNoMoreItems()
        }
    }
    
    private func shouldVerifyEmptyState(count: Int) {
        if count == 0 && self.paginationModel.items.count == 0 {
            self.presenter?.presentEmptyState()
            self.presenter?.presentRemoveNoMoreItems()
        }
    }
}
