//
//  PlaceCommentsInteractor.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceCommentsBusinessLogic {
    func shouldSetPlace(request: PlaceCommentsModels.PlaceSetup.Request)
    func shouldFetchItems()
    func shouldFetchImage(request: PlaceCommentsModels.ImageFetching.Request)
}

class PlaceCommentsInteractor: PlaceCommentsBusinessLogic, PlaceCommentsWorkerDelegate {
    var presenter: PlaceCommentsPresentationLogic?
    var worker: PlaceCommentsWorker?
    
    var placeId: String?
    var paginationModel: PlaceCommentsModels.PaginationModel
    
    init() {
        self.paginationModel = PlaceCommentsModels.PaginationModel()
        self.worker = PlaceCommentsWorker(delegate: self)
    }
    
    func shouldSetPlace(request: PlaceCommentsModels.PlaceSetup.Request) {
        self.placeId = request.placeId
    }
}

extension PlaceCommentsInteractor {
    func shouldFetchImage(request: PlaceCommentsModels.ImageFetching.Request) {
        let item = request.item
        if item.image == nil && item.imageName.isNilOrEmpty() {
            self.presenter?.presentPlaceholderImage(response: PlaceCommentsModels.ImagePresentation.Response(item: item, image: nil))
        } else if item.image == nil && !item.imageName.isNilOrEmpty() && !item.isLoadingImage {
            self.presenter?.presentWillFetchImage(response: PlaceCommentsModels.ImageFetching.Response(item: item))
            self.worker?.fetchImage(item: item)
        }
    }
    
    func successDidFetchImage(item: PlaceCommentsModels.DisplayedItem, image: UIImage?) {
        self.presenter?.presentImage(response: PlaceCommentsModels.ImagePresentation.Response(item: item, image: image))
        self.presenter?.presentDidFetchImage(response: PlaceCommentsModels.ImageFetching.Response(item: item))
    }
    
    func failureDidFetchImage(item: PlaceCommentsModels.DisplayedItem, error: OperationError) {
        self.presenter?.presentPlaceholderImage(response: PlaceCommentsModels.ImagePresentation.Response(item: item, image: nil))
        self.presenter?.presentDidFetchImage(response: PlaceCommentsModels.ImageFetching.Response(item: item))
    }
}

extension PlaceCommentsInteractor  {
    func shouldFetchItems() {
        if !self.paginationModel.isFetchingItems && !self.paginationModel.noMoreItems {
            self.paginationModel.isFetchingItems = true
            self.presenter?.presentWillFetchItems()
            self.worker?.fetchItems(placeId: self.placeId, page: self.paginationModel.currentPage, limit: self.paginationModel.limit)
        }
    }
    
    func successDidFetchItems(items: [Comment]) {
        self.paginationModel.items.append(contentsOf: items)
        self.paginationModel.currentPage += 1
        self.paginationModel.isFetchingItems = false
        self.paginationModel.hasError = false
        self.presenter?.presentDidFetchItems()
        self.presenter?.presentRemoveErrorState()
        self.presenter?.presentNewItems(response: PlaceCommentsModels.ItemsPresentation.Response(items: items))
        self.shouldVerifyNoMorePlaces(count: items.count)
        self.shouldVerifyEmptyState(count: items.count)
    }
    
    func failureDidFetchItems(error: OperationError) {
        self.paginationModel.isFetchingItems = false
        self.paginationModel.hasError = true
        self.presenter?.presentDidFetchItems()
        self.presenter?.presentErrorState()
    }
}

extension PlaceCommentsInteractor {
    private func shouldVerifyNoMorePlaces(count: Int) {
        if count < self.paginationModel.limit {
            self.paginationModel.noMoreItems = true
            self.presenter?.presentNoMoreItems()
        }
    }
    
    private func shouldVerifyEmptyState(count: Int) {
        if count == 0 && self.paginationModel.items.count == 0 {
            self.presenter?.presentEmptyState()
            self.presenter?.presentRemoveNoMoreItems()
        }
    }
}
