//
//  MainViewController+Subviews.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 12/09/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

extension MainViewController {
    func setupSubviews() {
        self.setupTabBar()
        self.setupContentView()
    }
    
    func setupTabBar() {
        self.tabBar.isTranslucent = MainStyle.shared.tabBarViewModel.isTranslucent
        self.tabBar.barTintColor = MainStyle.shared.tabBarViewModel.barTintColor
        self.tabBar.tintColor = MainStyle.shared.tabBarViewModel.tintColor
        self.tabBar.unselectedItemTintColor = MainStyle.shared.tabBarViewModel.unselectedItemTintColor
        self.tabBar.shadowImage = MainStyle.shared.tabBarViewModel.shadowImage
        self.tabBar.itemPositioning = .centered
    }
    
    func setupContentView() {
        self.view.backgroundColor = MainStyle.shared.contentViewModel.backgroundColor
    }
    
    func setupTabBarItem(item: UITabBarItem) {
        item.setTitleTextAttributes(MainStyle.shared.tabBarItemViewModel.selectedTextAttributes(), for: .selected)
        item.setTitleTextAttributes(MainStyle.shared.tabBarItemViewModel.unselectedTextAttributes(), for: .normal)
    }
}
