//
//  MyProfileViewControllerTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class MyProfileViewControllerTests: XCTestCase {
    var sut: MyProfileViewController!
    var interactorSpy: MyProfileBusinessLogicSpy!
    var routerSpy: MyProfileRoutingLogicSpy!
    var window: UIWindow!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.window = UIWindow()
        self.setupMyProfileViewController()
    }
    
    override func tearDown() {
        self.window = nil
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupMyProfileViewController() {
        self.sut = MyProfileViewController()
        
        self.interactorSpy = MyProfileBusinessLogicSpy()
        self.sut.interactor = self.interactorSpy
        
        self.routerSpy = MyProfileRoutingLogicSpy()
        self.sut.router = self.routerSpy
    }
    
    func loadView() {
        self.window.addSubview(self.sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: - Tests
    
    
}
