//
//  MyProfileInteractorTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 27/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class MyProfileInteractorTests: XCTestCase {
    var sut: MyProfileInteractor!
    var presenterSpy: MyProfilePresentationLogicSpy!
    var workerSpy: MyProfileWorkerSpy!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        self.setupMyProfileInteractor()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupMyProfileInteractor() {
        self.sut = MyProfileInteractor()
        
        self.presenterSpy = MyProfilePresentationLogicSpy()
        self.sut.presenter = self.presenterSpy
        
        self.workerSpy = MyProfileWorkerSpy(delegate: self.sut)
        self.sut.worker = self.workerSpy
    }
    
    // MARK: - Tests
  
    
}
