//
//  MyFavoritePlacesPresenterTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 11/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class MyFavoritePlacesPresenterTests: XCTestCase {
    var sut: MyFavoritePlacesPresenter!
    var displayerSpy: MyFavoritePlacesDisplayLogicSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupMyFavoritePlacesPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupMyFavoritePlacesPresenter() {
        self.sut = MyFavoritePlacesPresenter()
        
        self.displayerSpy = MyFavoritePlacesDisplayLogicSpy()
        self.sut.displayer = self.displayerSpy
    }
    
    // MARK: - Tests
    
    
}
