//
//  MyFavoritePlacesRouterTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 11/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class MyFavoritePlacesRouterTests: XCTestCase {
    var sut: MyFavoritePlacesRouter!
    var viewController: MyFavoritePlacesViewController!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupMyFavoritePlacesRouter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupMyFavoritePlacesRouter() {
        self.sut = MyFavoritePlacesRouter()
        
        self.viewController = MyFavoritePlacesViewController()
        self.sut.viewController = self.viewController
    }
    
    // MARK: - Tests
    
    func testNavigateToPlaceDetails() {
        let navigationControllerSpy = UINavigationControllerSpy(rootViewController: self.sut.viewController!)
        self.sut.navigateToPlaceDetails(place: Place(id: "placeId", location: Location(id: "locationId", latitude: 47, longitude: 27)))
        XCTAssertTrue(navigationControllerSpy.pushedViewController is PlaceDetailsViewController)
    }
}
