//
//  PlaceDetailsWorker.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaceDetailsWorkerDelegate: class {
    
}

class PlaceDetailsWorker {
    weak var delegate: PlaceDetailsWorkerDelegate?
    
    init(delegate: PlaceDetailsWorkerDelegate?) {
        self.delegate = delegate
    }
}
