//
//  ExploreViewController+Subviews.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

extension ExploreViewController {
    func setupSubviews() {
        self.setupNavigationBar()
        self.setupNavigationItem()
        self.setupContentView()
        self.setupTableView()
    }
    
    private func setupNavigationBar() {
        self.navigationController?.navigationBar.isTranslucent = ExploreStyle.shared.navigationBarModel.isTranslucent
        self.navigationController?.navigationBar.tintColor = ExploreStyle.shared.navigationBarModel.tintColor
        self.navigationController?.navigationBar.barTintColor = ExploreStyle.shared.navigationBarModel.barTintColor
        self.navigationController?.navigationBar.titleTextAttributes = ExploreStyle.shared.navigationBarModel.titleAttributes()
    }
    
    private func setupNavigationItem() {
        self.navigationItem.title = ExploreLocalization.shared.title
        self.navigationItem.searchController = self.setupSearchController()
        self.navigationItem.hidesSearchBarWhenScrolling = false
    }
    
    private func setupContentView() {
        self.definesPresentationContext = true
        self.view.backgroundColor = ExploreStyle.shared.contentViewModel.backgroundColor
    }
    
    func setupSearchController() -> UISearchController {
        let searchController = UISearchController(searchResultsController: nil)
        searchController.delegate = self
        searchController.searchResultsUpdater = self
        searchController.dimsBackgroundDuringPresentation = false
        searchController.searchBar.delegate = self
        return searchController
    }
    
    private func setupTableView() {
        self.tableView.backgroundColor = ExploreStyle.shared.tableViewModel.backgroundColor
        self.tableView.translatesAutoresizingMaskIntoConstraints = false
        self.tableView.separatorStyle = .none
        self.tableView.tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: CGFloat.leastNonzeroMagnitude))
        self.tableView.register(ExploreTableViewCell.self, forCellReuseIdentifier: ExploreTableViewCell.defaultReuseIdentifier)
    }
    
    func emptyStateView(image: UIImage?, attributedText: NSAttributedString?) -> EmptyStateView {
        let view = EmptyStateView(frame: self.tableView.frame)
        view.image = image
        view.attributedText = attributedText
        return view
    }
}
