name: "Build and run tests"
on: 
  pull_request:
    branches: ['master', 'development']

jobs:
  build_and_test:
    runs-on: macOS-latest

    timeout-minutes: 60

    env:
      XC_VERSION: ${{ '14.1' }}

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2

    - name: "Install system dependencies"
      run: |
        gem install bundler
        bundle install
      working-directory: Travelling

    - name: "Run tests"
      run: "bundle exec fastlane tests"
      working-directory: Travelling
