//
//  PlaceDetailsInteractorTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class PlaceDetailsInteractorTests: XCTestCase {
    var sut: PlaceDetailsInteractor!
    var presenterSpy: PlaceDetailsPresentationLogicSpy!
    var workerSpy: PlaceDetailsWorkerSpy!
  
    // MARK: - Test lifecycle
  
    override func setUp() {
        super.setUp()
        self.setupPlaceDetailsInteractor()
    }
  
    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupPlaceDetailsInteractor() {
        self.sut = PlaceDetailsInteractor()
        
        self.presenterSpy = PlaceDetailsPresentationLogicSpy()
        self.sut.presenter = self.presenterSpy
        
        self.workerSpy = PlaceDetailsWorkerSpy(delegate: self.sut)
        self.sut.worker = self.workerSpy
    }
    
    // MARK: - Tests
  
    
}
