//
//  PlaceDetailsWorkerTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 08/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class PlaceDetailsWorkerTests: XCTestCase {
    var sut: PlaceDetailsWorker!
    var delegateSpy: PlaceDetailsWorkerDelegateSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupPlaceDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupPlaceDetailsWorker() {
        self.delegateSpy = PlaceDetailsWorkerDelegateSpy()
        self.sut = PlaceDetailsWorker(delegate: self.delegateSpy)
    }
    
    // MARK: - Tests
    
    
}
