//
//  ExploreWorkerTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 13/09/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class ExploreWorkerTests: XCTestCase {
    var sut: ExploreWorker!
    var delegateSpy: ExploreWorkerDelegateSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupExploreWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupExploreWorker() {
        self.delegateSpy = ExploreWorkerDelegateSpy()
        self.sut = ExploreWorker(delegate: self.delegateSpy)
    }
    
    // MARK: - Tests
    
    func testFetchItemsShouldAskThePlacesTaskToFetchPlaces() {
        let taskSpy = PlacesTaskSpy()
        self.sut.placesTask = taskSpy
        self.sut.fetchItems(page: 0, limit: 30)
        XCTAssertTrue(taskSpy.fetchPlacesCalled)
    }
    
    func testFetchItemsShouldAskTheDelegateToSendPlacesForSuccessCase() {
        let taskSpy = PlacesTaskSpy()
        taskSpy.shouldFailFetchPlaces = false
        self.sut.placesTask = taskSpy
        self.sut.fetchItems(page: 0, limit: 30)
        XCTAssertTrue(self.delegateSpy.successDidFetchItemsCalled)
    }
    
    func testFetchItemsShouldAskTheDelegateToSendErrorForFailureCase() {
        let taskSpy = PlacesTaskSpy()
        taskSpy.shouldFailFetchPlaces = true
        self.sut.placesTask = taskSpy
        self.sut.fetchItems(page: 0, limit: 30)
        XCTAssertTrue(self.delegateSpy.failureDidFetchItemsCalled)
    }
    
    func testFetchImage() {
        let taskSpy = ImageTaskSpy()
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(item: ExploreModels.DisplayedItem(id: "id"))
        XCTAssertTrue(taskSpy.fetchImageCalled)
    }
    
    func testFetchImageShouldAskTheDelegateToSendImageForSuccessCase() {
        let taskSpy = ImageTaskSpy()
        taskSpy.shouldFailFetchImage = false
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(item: ExploreModels.DisplayedItem(id: "id"))
        XCTAssertTrue(self.delegateSpy.successDidFetchImageCalled)
    }
    
    func testFetchImageShouldAskTheDelegateToSendErrorForFailureCase() {
        let taskSpy = ImageTaskSpy()
        taskSpy.shouldFailFetchImage = true
        self.sut.imageTask = taskSpy
        self.sut.fetchImage(item: ExploreModels.DisplayedItem(id: "id"))
        XCTAssertTrue(self.delegateSpy.failureDidFetchImageCalled)
    }
}
