//
//  ForgotPasswordWorkerTests.swift
//  Travelling
//
//  Created by Dimitri Strauneanu on 05/10/2020.
//  Copyright (c) 2020 Travelling. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Travelling
import XCTest

class ForgotPasswordWorkerTests: XCTestCase {
    var sut: ForgotPasswordWorker!
    var delegateSpy: ForgotPasswordWorkerDelegateSpy!
    
    // MARK: - Test lifecycle
    
    override func setUp() {
        super.setUp()
        self.setupForgotPasswordWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupForgotPasswordWorker() {
        self.delegateSpy = ForgotPasswordWorkerDelegateSpy()
        self.sut = ForgotPasswordWorker(delegate: self.delegateSpy)
    }
    
    // MARK: - Tests
    
    func testSendResetLink() {
        let taskSpy = AuthenticationTaskSpy()
        self.sut.authenticationTask = taskSpy
        self.sut.sendResetLink(email: "Email")
        XCTAssertTrue(taskSpy.forgotPasswordCalled)
    }
    
    func testSendResetLinkShouldAskTheDelegateToSendMessageStringForSuccessCase() {
        let taskSpy = AuthenticationTaskSpy()
        taskSpy.shouldFailForgotPassword = false
        self.sut.authenticationTask = taskSpy
        self.sut.sendResetLink(email: "Email")
        XCTAssertTrue(self.delegateSpy.successDidSendResetLinkCalled)
    }
    
    func testSendResetLinkShouldAskTheDelegateToSendErrorForFailureCase() {
        let taskSpy = AuthenticationTaskSpy()
        taskSpy.shouldFailForgotPassword = true
        self.sut.authenticationTask = taskSpy
        self.sut.sendResetLink(email: "Email")
        XCTAssertTrue(self.delegateSpy.failureDidSendResetLinkCalled)
    }
}
